line = "I love python"
print(len(line))
print(line.index("l"))
print(line.replace("p",'j'))
print(line.split(" "))
print(line.upper())
print(line.lower())
print(line.title())
print(line.islower())
print(line.isupper())
print(line.count('o'))